!     Last change:  JD   12 Feb 2001    2:26 pm

program fac2fefl

! -- Program FAC2FEFL modifies a FEFLOW input file, replacing element values for a particular
!    property with those interpolated from pilot points using kriging factors generated by the
!    PPK2FAC_FEFL utility.

        use defn
        use inter

        implicit none

        integer, parameter    :: MAXENT=100
        integer               :: ifail,facunit,ierr,ncol,nrow,nerr,nbb, &
                                 icellno,na,icol,irow,i,itrans,nnppt,outunit,ielem
        integer               :: irep,iline,nn,ii,j,jj,iend,ifin,istart,inunit
        integer               :: carrydash,carrynode,idash,ndash
        integer, allocatable, dimension(:)  :: ipt
        integer, dimension(MAXENT)          :: dashpos(MAXENT),inode(MAXENT),inodedash(MAXENT)
        real                                :: backval,rtemp,sum,rtemp1,rlo,rhi,rtemp2
        real, allocatable, dimension(:)     :: wt
        double precision                    :: dval,startval
        character (len=1)                   :: facformat,arealformat,alimit
        character (len=5)                   :: acode
        character (len=10)                  :: aline
        character (len=20)                  :: atemp
        character (len=20)                  :: datname
        character (len=200)                 :: aprompt,facfile,afile,intfile,outfile,infile
        character (len=500)                 :: dline
        character (len=12), allocatable, dimension(:)    :: wpoints


        write(amessage,5)
5        format(' Program FAC2FEFL carries out spatial interpolation for a FEFLOW model based on ', &
        'interpolation factors calculated by PPK2FAC_FEFL and pilot point values contained ', &
        'in a pilot points file.')
        call write_message(leadspace='yes',endspace='yes')

! -- The first two lines of the interpolation factor file are read.

10      aprompt=' Enter name of interpolation factor file: '
        call open_input_file(ifail,aprompt,facfile,facunit,form_prompt='yes', &
        fformat=facformat)
        if(ifail.ne.0) go to 9900
        if(escset.ne.0) go to 9900

        if(facformat.eq.'f')then
          read(facunit,'(a)',err=9000,end=9100) afile
        else
          read(facunit,err=9000,end=9100) afile
        end if
        afile=adjustl(afile)
        nbb=len_trim(afile)
        call getfile (ifail,afile,pilot_points_file,1,nbb)
        if(ifail.ne.0)pilot_points_file=' '

        if(facformat.eq.'f')then
          read(facunit,'(a)',err=9000,end=9100) afile
        else
          read(facunit,err=9000,end=9100) afile
        end if
        afile=adjustl(afile)
        if(afile.eq.' ')then
          intfile=' '
        else
          nbb=len_trim(afile)
          call getfile (ifail,afile,intfile,1,nbb)
          if(ifail.ne.0)intfile=' '
        end if

        if(facformat.eq.'f')then
          read(facunit,*,err=9000,end=9100) numelem_f
        else
          read(facunit,err=9000,end=9100) numelem_f
        end if
        
        if(facformat.eq.'f')then
          read(facunit,*,err=9000,end=9100) nnppt
        else
          read(facunit,err=9000,end=9100) nnppt
        end if
        allocate(wpoints(nnppt),stat=ierr)
        if(ierr.ne.0) then
          write(amessage,50)
50        format(' Cannot allocate sufficient memory to run FAC2FEFL.')
          go to 9890
        end if
        if(facformat.eq.'f')then
          do i=1,nnppt
            read(facunit,'(a)',err=9000,end=9100) wpoints(i)
          end do
        else
          do i=1,nnppt
            read(facunit,err=9000,end=9100) wpoints(i)
          end do
        end if
        do i=1,nnppt
          wpoints(i)=adjustl(wpoints(i))
          call casetrans(wpoints(i),'hi')
        end do

! -- The pilot points file is read.

        write(6,*)
80      call read_pilot_points_file(ifail, &
        ' Enter name of pilot points file: ')
        if(ifail.ne.0) go to 9900
        if(escset.ne.0) then
          escset=0
          deallocate(wpoints,stat=ierr)
          if(ierr.ne.0) then
            write(amessage,57)
57          format(' Memory management error: cannot continue execution.')
            go to 9890
          end if
          close(unit=facunit)
          write(6,*)
          go to 10
        end if
        if(nnppt.ne.num_pilot_points)then
          write(amessage,59)
          go to 9890
        else
          do i=1,num_pilot_points
            if(pilot_point_id(i).ne.wpoints(i))then
              write(amessage,59)
59            format(' The pilot points in the pilot points file are not the same, ', &
              'or are not arranged in the same order, as the pilot points in the ', &
              'pilot points file read by PPK2FAC_FEFL when it calculated the ', &
              'interpolation factors contained in the factor file.')
              go to 9890
            end if
          end do
        end if

! -- Interpolation upper and lower limits are supplied.

        write(6,*)
270     write(6,280,advance='no')
280     format(' Enter lower interpolation limit: ')
        if(key_read(rlo).ne.0) go to 270
        if(escset.eq.1) then
          write(6,*)
          escset=0
          go to 80
        end if

310     write(6,320,advance='no')
320     format(' Enter upper interpolation limit: ')
        if(key_read(rhi).ne.0) go to 310
        if(escset.eq.1) then
          write(6,*)
          escset=0
          go to 270
        end if
        if(rlo.ge.rhi)then
          write(6,330)
330       format(/,' Upper limit must be greater than lower limit - try again.',/)
          go to 310
        end if

! -- The output file is written.

        write(6,*)
331     call open_output_file(ifail, &
        ' Enter name for update file: ',outfile,outunit)
	if(ifail.ne.0) go to 9900
	if(escset.ne.0) then
          escset=0
          write(6,*)
          go to 310
        end if
                
! -- The interpolation factor file is now read line by line and the factors
!    are used to undertake spatial interpolation.

        allocate(ipt(num_pilot_points),wt(num_pilot_points),stat=ierr)
        if(ierr.ne.0) then
          write(amessage,50)
          go to 9890
        end if

        write(6,351)
351     format(/,' - interpolating from pilot points to finite element mesh...')

        do
          if(facformat.eq.'f')then
            read(facunit,*,err=9000,end=600) icellno,itrans, &
            na,rtemp,((ipt(i),wt(i)),i=1,na)
          else
            read(facunit,err=9000,end=600)   icellno,itrans, &
            na,rtemp,((ipt(i),wt(i)),i=1,na)
          end if
          sum=rtemp
          do i=1,na
            if(itrans.eq.0)then
              sum=sum+pilot_point_val(ipt(i))*wt(i)
            else
              rtemp2=pilot_point_val(ipt(i))
              if(rtemp2.le.0.0)then
                write(amessage,125)
125             format(' The interpolation factor file specifies that spatial ', &
                'interpolation in at least one zone takes place on the basis of the ', &
                'logarithms of pilot point values. However at least one of the ', &
                'pertinent pilot point values is negative.')
                go to 9890
              end if
              sum=sum+log10(rtemp2)*wt(i)
            end if
          end do
          if(itrans.eq.0)then
            rtemp1=sum
          else
            rtemp1=10**sum
          end if
          if(rtemp1.gt.rhi)then
            rtemp1=rhi
          else if(rtemp1.lt.rlo)then
            rtemp1=rlo
          end if
          write(outunit,599) icellno,rtemp1
599       format(i10,1pg14.7)        
        end do
600     continue

1000    continue

! -- Tidying up.

        close(unit=outunit)
        write(6,1020) trim(outfile)
1020    format(' - file ',a,' written ok.')

        go to 9900

9000    write(amessage,9010) trim(facfile)
9010    format(' Error encountered in reading interpolation factor file ',a)
        go to 9890
9100    write(amessage,9110) trim(facfile)
9110    format(' Unexpected end encountered to file ',a)
        go to 9890

9890    call write_message(leadspace='yes',endspace='yes')
9900    call close_files
        deallocate(ipt,wt,wpoints,stat=ierr)


end program fac2fefl



